### PR TITLE
MNT: Re-rendered with conda-build 3.19.1, conda-smithy 3.6.15, and conda-forge-pinning 2020.03.30

### PR DESCRIPTION
**Pull request by tschoonj**
For some reason I cannot install this package in my conda environment with python 3.7, and insists on python 3.5 instead. A rerender should bring this in order again...

### CODE REVIEW

**Comment by tschoonj** [comment]
@pmlandwehr Can you merge this PR in if you have a moment? Many thanks in advance!

**Comment by tschoonj** [comment]
@beckermr @isuruf Could either of you please merge this one in? It appears to be abandoned and its packages don't work with the latest python releases...

Thanks in advance!

**Comment by beckermr** [comment]
@tschoonj would you be willing to add yourself to the maintainers here?

**Comment by tschoonj** [comment]
Sure, I will push a commit for that

**Comment by tschoonj** [comment]
Done!

**Comment by beckermr** [comment]
k - i'm gonna rerender via the bot one more time and then we can merge

@conda-forge-admin rerender

**Comment by tschoonj** [comment]
Thanks!

**Pull request merged**
